// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"src/models"
)

// ListSingleProductsReader is a Reader for the ListSingleProducts structure.
type ListSingleProductsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSingleProductsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListSingleProductsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewListSingleProductsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListSingleProductsOK creates a ListSingleProductsOK with default headers values
func NewListSingleProductsOK() *ListSingleProductsOK {
	return &ListSingleProductsOK{}
}

/*
ListSingleProductsOK describes a response with status code 200, with default header values.

Data structure representing a single product
*/
type ListSingleProductsOK struct {
	Payload *models.Product
}

// IsSuccess returns true when this list single products o k response has a 2xx status code
func (o *ListSingleProductsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list single products o k response has a 3xx status code
func (o *ListSingleProductsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list single products o k response has a 4xx status code
func (o *ListSingleProductsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list single products o k response has a 5xx status code
func (o *ListSingleProductsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list single products o k response a status code equal to that given
func (o *ListSingleProductsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListSingleProductsOK) Error() string {
	return fmt.Sprintf("[GET /products/{id}][%d] listSingleProductsOK  %+v", 200, o.Payload)
}

func (o *ListSingleProductsOK) String() string {
	return fmt.Sprintf("[GET /products/{id}][%d] listSingleProductsOK  %+v", 200, o.Payload)
}

func (o *ListSingleProductsOK) GetPayload() *models.Product {
	return o.Payload
}

func (o *ListSingleProductsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Product)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSingleProductsNotFound creates a ListSingleProductsNotFound with default headers values
func NewListSingleProductsNotFound() *ListSingleProductsNotFound {
	return &ListSingleProductsNotFound{}
}

/*
ListSingleProductsNotFound describes a response with status code 404, with default header values.

Generic error message returned as a string
*/
type ListSingleProductsNotFound struct {
	Payload *models.GenericError
}

// IsSuccess returns true when this list single products not found response has a 2xx status code
func (o *ListSingleProductsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list single products not found response has a 3xx status code
func (o *ListSingleProductsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list single products not found response has a 4xx status code
func (o *ListSingleProductsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this list single products not found response has a 5xx status code
func (o *ListSingleProductsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this list single products not found response a status code equal to that given
func (o *ListSingleProductsNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *ListSingleProductsNotFound) Error() string {
	return fmt.Sprintf("[GET /products/{id}][%d] listSingleProductsNotFound  %+v", 404, o.Payload)
}

func (o *ListSingleProductsNotFound) String() string {
	return fmt.Sprintf("[GET /products/{id}][%d] listSingleProductsNotFound  %+v", 404, o.Payload)
}

func (o *ListSingleProductsNotFound) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *ListSingleProductsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
